package hoods.com.audioplayer.media.constants

object K {
    const val PLAYBACK_NOTIFICATION_CHANNEL_ID = "TYPOSBRO_PLAYBACK_NOTIFICATION_CHANNEL_ID"
    const val PLAYBACK_NOTIFICATION_ID = 23072014
    const val MEDIA_ROOT_ID = "TYPOSBRO_MEDIA_ROOT_ID"
    const val START_MEDIA_PLAYBACK_ACTION = "START_MEDIA_PLAYBACK_ACTION"
    const val REFRESH_MEDIA_PLAYBACK_ACTION = "REFRESH_MEDIA_PLAYBACK_ACTION"
    const val PLAYBACK_UPDATE_INTERVAL = 1000L

}